services:
  funasr:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bytedesk-ttsasr
    ports:
      - "8000:8000"
    environment:
      FUNASR_DEVICE: cpu
      FUNASR_MODEL: iic/SenseVoiceSmall
      FUNASR_VAD_MODEL: fsmn-vad
    restart: unless-stopped